### ISSUE TITLE
Plain text and punctuation unreadable

### ISSUE THREAD

**Issue by rcrooks** [ArthurMaverick/Brasil-theme#1]
Hi @ArthurMaverick ,

I love the color scheme, but alas, it's unusable for HTML -- plain text and punctuation are so close to the background color as to be unreadable. Attaching a screenshot to illustrate.
Best,
Robert
<img width="1049" alt="2020-09-12_09-54-01" src="https://user-images.githubusercontent.com/619617/92997051-38bc4100-f4de-11ea-86d0-00466ce152dc.png">

**Comment by ArthurMaverick** [comment]
Hello @rcrooks 
Thank you very much for your feedback. The version theme (0.0.1) was under development and I had to put it into production to do some tests. Now the version (0.2.1) has a better color harmony. My goal is to make up to version (1.0.0) the theme with the face of Brazil.

**Comment by rcrooks** [comment]
Thanks @ArthurMaverick that's much better :)

**Comment by ArthurMaverick** [comment]
I thank you for the recognition @rcrooks
